project:
  type: website
  output-dir: docs

website:
  page-footer: "Site content created for PSTAT197A Fall 2022 by Trevor Ruiz using Quarto; hex logo by Priscilla Siow."
  # reader-mode: true
  repo-url: "https://github.com/pstat197/pstat197a"
  sidebar:
    title: "Data Science Capstone Preparation"
    style: "docked"
    search: true
    logo: "img/ucsbds_hex.png"
    tools: 
      - icon: github
        href: https://github.com/pstat197
      - icon: slack
        href: https://ucsbdscapstone.slack.com
    contents:
      - section: "About"
        contents:
          - about/syllabus.qmd
          - about/outcomes.qmd
          - about/schedule.qmd
          - about/technology.qmd
          - about/links.qmd
      # - materials/course-materials.qmd  
          
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

