project:
  type: website
  output-dir: docs

website:
  title: "PSTAT197A: DS Capstone Preparation"
  # reader-mode: true
  repo-url: "https://github.com/pstat197/pstat197a"
  sidebar:
    title: "PSTAT197A: DS Capstone Preparation"
    style: "docked"
    search: true
    logo: "img/ucsbds_hex.png"
    tools: 
      - icon: github
        href: https://github.com/pstat197
      - icon: slack
        href: https://ucsbdscapstone.slack.com
    contents:
      - section: "About"
        contents:
          - syllabus.qmd
          - philosophy.qmd
          - technology.qmd
          - links.qmd
      - section: "Materials"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

