project:
  type: website
  output-dir: docs

website:
  # title: "PSTAT197A: Capstone Preparation"
  # reader-mode: true
  repo-url: "https://github.com/pstat197/pstat197a"
  sidebar:
    title: "Data Science Capstone Preparation"
    style: "docked"
    search: true
    logo: "img/ucsbds_hex.png"
    tools: 
      - icon: github
        href: https://github.com/pstat197
      - icon: slack
        href: https://ucsbdscapstone.slack.com
    contents:
      - section: "About"
        contents:
          - about/syllabus.qmd
          - about/schedule.qmd
          - about/philosophy.qmd
      - section: "Course materials"
        contents:
          - materials/lab-activities.qmd
          - materials/technology.qmd
          - materials/links.qmd
          
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

