project:
  type: website
  output-dir: docs

website:
  page-footer: "Site content created by Trevor Ruiz using Quarto; hex logo by Priscilla Siow."
  # reader-mode: true
  repo-url: "https://github.com/pstat197/pstat197.github.io"
  sidebar:
    title: "Data Science Capstone"
    style: "docked"
    search: true
    logo: "img/ucsbds_hex.png"
    tools: 
      - icon: github
        href: https://github.com/pstat197
      - icon: slack
        href: https://ucsbdscapstone.slack.com
    contents:
      - about/info-for-students.qmd
      - section: "Projects"
        contents:
          - projects/projects-22-23.qmd
      - section: "PSTAT197A"
        contents:
          - pstat197a/about-syllabus.qmd
          - pstat197a/about-outcomes.qmd
          - pstat197a/about-schedule.qmd
          - pstat197a/about-technology.qmd
          - pstat197a/about-links.qmd
          - pstat197a/index-course-materials.qmd
      - section: "PSTAT197B-C"
        contents:
          - pstat197bc/about-syllabus.qmd
          - pstat197bc/about-schedule.qmd
          - pstat197bc/index-class-meetings.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

